### ISSUE TITLE
Testing Logs

### ISSUE THREAD

**Issue by sven-7** [Dingmatt/AMSA#1] opened 2017-03-12 00:38 UTC
Hi @Dingmatt  -- I added a test library and AMSA (with ASS), but it didn't seem to go very well.  So much so, that I think there is probably something else affecting this, but here are the logs.

[AMSA Test.zip](https://github.com/Dingmatt/AMSA/files/836217/AMSA.Test.zip)

<img width="1559" alt="screen shot 2017-03-11 at 7 36 13 pm" src="https://cloud.githubusercontent.com/assets/18091557/23828050/659e9508-0692-11e7-8132-a41288d5cd5d.png">

**Comment by Dingmatt** [comment] 2017-03-12 01:14
@sven-7 Thanks for taking the time. The logs seems to suggest that its settings file (DefaultPrefs.json) is corrupt; that would also explain the other errors we're seeing.

Could you try replacing it with the fresh one in the zip attached (it goes in 'Plex Media Server\Plug-ins\Amsa_Test.bundle\Contents')?
[DefaultPrefs.zip](https://github.com/Dingmatt/AMSA/files/836238/DefaultPrefs.zip)

**Comment by sven-7** [comment] 2017-03-12 02:30
No problem -- glad to help. I replaced that file, but the results are much of the same. Here is the next batch of logs (I have not looked through it just yet).

[com.plexapp.agents.amsa_test.log.zip](https://github.com/Dingmatt/AMSA/files/836256/com.plexapp.agents.amsa_test.log.zip)

**Comment by Dingmatt** [comment] 2017-03-12 03:27
@sven-7 thanks again and I've figured out the issue. I haven't yet coded HAMA's various additional modes (TvDB2, TvDB3, etc) into AMSA (was the next thing on my list) so its getting confused and is unable to find a match. 

I'm working on a very basic fix now, it won't give full functionality but will allow it to grab some of the meta whilst I finalize the code.

**Comment by Dingmatt** [comment] 2017-03-12 03:49
@sven-7 could I trouble you to try this latest version, it probably won't be able correctly display the various custom modes (I'll get to that later) but it should be able to match correctly and show some meta data.
[Amsa_Test.bundle 201703120345.zip](https://github.com/Dingmatt/AMSA/files/836277/Amsa_Test.bundle.201703120345.zip)

**Comment by sven-7** [comment] 2017-03-12 04:26
Here you go.  Similar results again.

If you want, I can remove those series from this test library.  Let me know -- happy to do so.

[com.plexapp.agents.amsa_test4.zip](https://github.com/Dingmatt/AMSA/files/836293/com.plexapp.agents.amsa_test4.zip)

**Comment by Dingmatt** [comment] 2017-03-12 05:08
@sven-7 if you happy to help me test until things work then by all means leave them in, here's my last version for tonight (I'll pick it up again tomorrow); if you get similar errors (think I know whats going on) then could you include a zipped version of your 'bundles' directory (\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.amsa_test\DataItems\Cache\Bundles) as that will help me get an understanding of what data's getting stored.

Thanks again.

[Amsa_Test.bundle 201703120504.zip](https://github.com/Dingmatt/AMSA/files/836300/Amsa_Test.bundle.201703120504.zip)

**Comment by sven-7** [comment] 2017-03-12 05:42
No worries at all.  Here you go.

[Amsa5.zip](https://github.com/Dingmatt/AMSA/files/836307/Amsa5.zip)

**Comment by Dingmatt** [comment] 2017-03-12 12:04
@sven-7 Ok, it looks this the issues a little further forward in the process to what I was expecting. I'll reply once I've got something to test. Thanks again.

**Comment by Dingmatt** [comment] 2017-03-12 13:50
@sven-7 Well I've taken a look at the latest logs and found the cause. The way your files were being ignored by the agent as it was being a little too stringent about its absolute file naming, I've expanded this to include a broader scope.

Can you give this one a try for me, thanks in advance.
[Amsa_Test.bundle 201703121347.zip](https://github.com/Dingmatt/AMSA/files/836543/Amsa_Test.bundle.201703121347.zip)

**Comment by sven-7** [comment] 2017-03-12 19:03
Okay, seeing some progress.  Here is a screen shot, the logs, and the bundles again.

[AMSA6.zip](https://github.com/Dingmatt/AMSA/files/836814/AMSA6.zip)

<img width="943" alt="screen shot 2017-03-12 at 3 03 19 pm" src="https://cloud.githubusercontent.com/assets/18091557/23834932/0cf1fa6e-0735-11e7-905e-77617c5da019.png">

**Comment by Dingmatt** [comment] 2017-03-12 19:21
@sven-7 yay good news. How are you specifying which series is using which custom mode (tvdb2, etc)? If its a file would you mind attaching an example (say for Berserk (2016))? That'll allow me to recreate the same file structure and sort thing out direct.

**Comment by sven-7** [comment] 2017-03-12 19:46
I know! Good news indeed.

Yep, no problem! Here is the file list.  Within the tvdb2.id file I only have the TVDB code (in this case it is: 307111)

```
Berserk (2016)\Berserk (2016) - 0x01 - Golden Age Arc I Egg of the King.mkv
Berserk (2016)\Berserk (2016) - 0x02 - Golden Age Arc II The Battle for Doldrey.mkv
Berserk (2016)\Berserk (2016) - 0x03 - Golden Age Arc III The Advent.mkv
Berserk (2016)\Berserk (2016) - 1 - The Branded Swordsman.mkv
Berserk (2016)\Berserk (2016) - 10 - Hell's Angels.mkv
Berserk (2016)\Berserk (2016) - 11 - Shadows of Ideas.mkv
Berserk (2016)\Berserk (2016) - 12 - Those Who Cling, Those Who Struggle.mkv
Berserk (2016)\Berserk (2016) - 2 - The Holy Iron Chain Knights.mkv
Berserk (2016)\Berserk (2016) - 3 - Night of Miracles.mkv
Berserk (2016)\Berserk (2016) - 4 - Revelations.mkv
Berserk (2016)\Berserk (2016) - 5 - Tower of Conviction.mkv
Berserk (2016)\Berserk (2016) - 6 - A Nighttime Feast Burning at the Stake.mkv
Berserk (2016)\Berserk (2016) - 7 - The Black Witch.mkv
Berserk (2016)\Berserk (2016) - 8 - Reunion in the Den of Evil.mkv
Berserk (2016)\Berserk (2016) - 9 - Blood Flow of the Dead.mkv
Berserk (2016)\tvdb2.id
```

**Comment by Dingmatt** [comment] 2017-03-12 20:08
@sven-7 Ok seems like I still hadn't completely fixed the absolute file naming issue, I've completely reworked the matching pattern which should now work for 99% of circumstances.

For the record it ignores episodes which **don't** meet the following criteria (case insensitive):
- Includes 'SxxExx' in the filename, or
- Includes 'ncop' in the filename, or
- Includes 'op' in the filename, or
- Includes 'nced' in the filename, or
- Includes 'ed' in the filename, or
- Includes '- x -' in the filename, or
- Includes '- Ex -' in the filename, or
- Includes '- Ax -' in the filename, or
- Includes '- ABSx -' in the filename, or

I'm hoping this version will match the remaining in you library.

[Amsa_Test.bundle 201703121958.zip](https://github.com/Dingmatt/AMSA/files/836860/Amsa_Test.bundle.201703121958.zip)

**Comment by sven-7** [comment] 2017-03-12 20:25
So...oddly enough, now AMSA doesn't show up as a plug-in. I'll see if it's a browser caching something weird.

**Comment by Dingmatt** [comment] 2017-03-12 21:04
@sven-7 Interesting. If it doesn't reappear let me know and I'll upload another version.

**Comment by sven-7** [comment] 2017-03-12 21:16
Yeah, no luck. I probably won't have a chance to test until tomorrow again. Will test whatever latest version you list later.

**Comment by Dingmatt** [comment] 2017-03-12 21:24
@sven-7 My fault, managed to introduce a error when making the last change; didn't see it until I restarted my own Plex.

[Amsa_Test.bundle 201703122123.zip](https://github.com/Dingmatt/AMSA/files/836923/Amsa_Test.bundle.201703122123.zip)

**Comment by sven-7** [comment] 2017-03-12 21:49
Okay, no worries. I'll run this (or if you update one) late tonight when I get home or in the morning. 

So far, I'm just using a subset, library. My thoughts were to do my full library after that. As long as they're separate libraries, there shouldn't be any issue with HAMA and AMSA calling on the same files, right?

**Comment by Dingmatt** [comment] 2017-03-12 21:55
No there shouldn't be any issues, I've been running the Hama tests with that setup and haven't had a single problem.

You don't need to cause yourself any inconvenience, I'm just happy to get a bit of feedback and patch these issues; whenever your free is fine.

Thanks again.

**Comment by sven-7** [comment] 2017-03-12 22:17
Not at all -- I'm happy to help. Not being technical, I figure being a tester is the best I can offer with development! 

I'll run your latest version on the full library.

**Comment by sven-7** [comment] 2017-03-14 01:02
Okay - had a chance to run this.  It seemed to work pretty well.  Seems like some errors are in the logs. It took forever.  I actually stopped it as it had been going for over an hour.  The logs unfortunately got too big and started overwriting themselves, but I grabbed two batches.

[AMSA Logs .zip](https://github.com/Dingmatt/AMSA/files/839983/AMSA.Logs.zip)

**Comment by Dingmatt** [comment] 2017-03-14 01:16
I know that TVDB's been having a few issues today and the logs you've attached seem to confirm that, more often than no the connection timing out or at best running at a crawl. It also looks like you might be suffering from a temporary AniDB ban (don't worry it'll lift after a few hours, a day at most; though power cycling your modem will likely fix it sooner as your IP will change), I've recently seen the same when both Hama and Amsa decided to clear there cache at the same time.

Seems theirs still a couple of cases where series aren't matching but that could be because of the above. Thanks again for the feedback, every bit helps.

**Comment by sven-7** [comment] 2017-03-14 01:39
Been through the AniDB ban quite a few times. Happens when doing a whole library like this. I'll run a refresh again later. I've left the library in tact, so I'll monitor and upload more logs later. Let me know if you need anything else with it.

**Comment by sven-7** [comment] 2017-03-14 03:37
Here is another.

[com.plexapp.agents.amsa_test.zip](https://github.com/Dingmatt/AMSA/files/840217/com.plexapp.agents.amsa_test.zip)

**Comment by Dingmatt** [comment] 2017-03-14 10:30
Hi @sven-7.

It looks like Plex has cached the banned AniDB response, I'll look into a way of sorting this in the agent (already have an idea) but in the meantime could you delete the contents of your '\Plex Media Server\Plug-in Support\Caches\com.plexapp.agents.amsa_test' directory.

**Comment by sven-7** [comment] 2017-03-14 20:43
[com.plexapp.agents.amsa_test.zip](https://github.com/Dingmatt/AMSA/files/842633/com.plexapp.agents.amsa_test.zip)

**Comment by Dingmatt** [comment] 2017-03-14 20:59
@sven-7 Could you me a favour and try browsing to the following url, the logs still seem to suggest that you can't access AniDB but it'll be good to get confirmation of that.

[http://api.anidb.net:9001/httpapi?request=anime&client=amsa&clientver=1&protover=1&aid=7725 ](http://api.anidb.net:9001/httpapi?request=anime&client=amsa&clientver=1&protover=1&aid=7725 )

**Comment by sven-7** [comment] 2017-03-14 21:09
Still banned.

**Comment by Dingmatt** [comment] 2017-03-14 21:10
It might be worth leaving it a few days so that isn't extended any further, the last thing I'd want to happen is have you unable to access metadata for your regular Plex libraries.

**Comment by sven-7** [comment] 2017-03-14 21:12
I've had this happen before when adding the full library like that.  I'll delete it and add it in several pieces in a day or two so that I can avoid triggering the ban again.

**Comment by Dingmatt** [comment] 2017-03-14 21:16
I'll release a new version with a slightly longer AniDB Anti-Ban delay, in theory it should be once every 2 seconds but maybe its cutting it too close.

**Comment by Dingmatt** [comment] 2017-03-15 04:21
Hi Sven-7, Just thought I'd give you access to the latest version of the agent. This version has improved search / matching rates and speed as well as a slightly longer AniDB Anti-Ban delay.

[Amsa_Test.bundle_201703150418.zip](https://github.com/Dingmatt/AMSA/files/843431/Amsa_Test.bundle_201703150418.zip)

**Comment by sven-7** [comment] 2017-03-17 19:00
I'll run some more tests this weekend.

**Comment by begna112** [comment] 2017-03-19 05:59
I think i'm having related problems. I read above something about the strictness of the filename scanner. I refuse to rename my anime files from the original release names and I think others are the same way. Perhaps you should accommodate that naming scheme? Like so: [http://i.imgur.com/HSVuWPz.png](url)

My plex anime libary looks like this: [http://i.imgur.com/uBJotch.png](url)

Idk where to find logs but if you point me in the right direction, i'm happy to provide.

**Comment by Dingmatt** [comment] 2017-03-19 08:41
@begna112 that shouldn't be a problem though the images you've linked don't work, could you send over a new set?

**Comment by Dingmatt** [comment] 2017-03-19 11:26
@sven-7 @begna112 Here's a new version for you to play around with, the changes are as follows:

- To correct an unrelated bug I've removed all file-naming restrictions.
- I've added the draft code for theme music (not active yet but will be in the next version)
- Corrected an issue cause slowdown to the metadata download 

Please note that I haven't optimized the way the agent handles its data yet so there are time its performing tasks that aren't necessary (i.e. overwriting data with exactly the same data), this will be corrected once I've sorted out these bugs we're seeing so I expect to see the scan time reduce. 
Additionally please remember that unlike Hama, Amsa does all its data processing at the time it detects a new show, this means that your first scan will be slower but any follow ups will be a lot faster

[Amsa_Test.bundle_201703191117.zip](https://github.com/Dingmatt/AMSA/files/853144/Amsa_Test.bundle_201703191117.zip)

**Comment by begna112** [comment] 2017-03-20 07:43
I've updated to the new bundle but I'm still not getting images. It seems to still be doing something though as it's still got a little spinning icon sometimes. I'll update in the morning.

**Comment by Dingmatt** [comment] 2017-03-20 10:43
@begna112 If it still isn't working then can you send me over the bundle files and logs, they can be found in the following locations:

- Bundles - "Plex Media Server\Plug-in Support\Data\com.plexapp.agents.amsa_test\DataItems\Cache\Bundles"
- Logs - "Plex Media Server\Logs\PMS Plugin Logs" (com.plexapp.agents.amsa_test.log, one through to five)

Thanks,

**Comment by namaless** [comment] 2017-03-20 23:18
Many replies here but at the start I found the same problem. The maching working fine because the metadata it's true but the cover not working. If I can post everything please explain me what you need.

**Comment by Dingmatt** [comment] 2017-03-21 00:02
@namaless yes, its looking like theirs a common problem which I need to track down but with everyone helping me that shouldn't take too long.

Firstly can you ensure your using the latest version found here: [Amsa_Test.bundle_201703191117.zip](https://github.com/Dingmatt/AMSA/files/853144/Amsa_Test.bundle_201703191117.zip)

After that can you try a refresh within Plex and send me over the bundle files and logs, they can be found in the following locations:

- Bundles - "Plex Media Server\Plug-in Support\Data\com.plexapp.agents.amsa_test\DataItems\Cache\Bundles"
- Logs - "Plex Media Server\Logs\PMS Plugin Logs" (com.plexapp.agents.amsa_test.log, one through to five)

Thanks,

**Comment by begna112** [comment] 2017-03-21 21:23
Well, for one thing, @Dingmatt, the plugin is making that as a new folder here: \Plex Media Server\Plug-in Support\Data\com.plexapp.agents.amsa\DataItems\Cache (note without the "-test"). And there's no "bundles" folder in there. 

Here's the cache though:
[Cache.zip](https://github.com/Dingmatt/AMSA/files/859684/Cache.zip)

And here's the logs:
[PMS Plugin Logs.zip](https://github.com/Dingmatt/AMSA/files/859690/PMS.Plugin.Logs.zip)

**Comment by namaless** [comment] 2017-03-21 21:56
[Bundles.zip](https://github.com/Dingmatt/AMSA/files/859765/Bundles.zip)
[PMS Plugin Logs.zip](https://github.com/Dingmatt/AMSA/files/859769/PMS.Plugin.Logs.zip)
Now for me the cover working fine, I removed the association and made another one and the cover is ok, i post what you need. Ask me everything I can do :)

**Comment by Dingmatt** [comment] 2017-03-21 22:35
Hi @begna112, could you confirm if you've been using a cloned version of the v0.1.4 branch or the latest versions on this thread? also if you've ever had a previous version installed. The reason I ask is I've never seen Plex create a directory with a name different from the logging file, until now I though they were tied.

**Comment by Dingmatt** [comment] 2017-03-21 22:50
@namaless thanks nameless, I've managed to spot a potential bug in your logs which I'm going to correct (the hanfdeling of metadata for unreleased episodes). I'll also be releasing a new demo version soon with all the fixes from this thread and a few speed increases.

**Comment by namaless** [comment] 2017-03-21 22:55
@Dingmatt  Im a developer (you can see my profile here) but Im noob for plex, but you can ask me everything. Thanks for your hard work!

**Comment by begna112** [comment] 2017-03-21 23:08
@Dingmatt I've been updating as you release new versions. I'll update to that version again to be sure.

**Comment by Dingmatt** [comment] 2017-03-21 23:10
@begna112 ok, if you can also check that your bundle directory (in the 'Plug-ins' folder) is called 'Amsa_Test.bundle', if not the rename it (you best restart plex after doing that).

**Comment by begna112** [comment] 2017-03-21 23:59
\binhex-plexpass\Plex Media Server\Plug-ins :
http://i.imgur.com/Kk7cFif.png

\Plex Media Server\Plug-in Support\Data
http://i.imgur.com/AnIIjVR.png
(again, I completely deleted all the amsa stuff and it recreated it here.)

Is there some way in the UI to delete it entirely? I deleted these while plex wasn't running. 

Still no show images. http://i.imgur.com/Q1QDwOV.png

**Comment by Dingmatt** [comment] 2017-03-22 00:52
Hi @begna112, did it create both the 'Data\com.plexapp.agents.amsa_test' and ''Data\com.plexapp.agents.amsa' directories (I'm assuming so looking at the created dates)?

There must be something off with the install, can you do the following "plugin dance" for me:

1. Stop Plex
1. Delete the Amsa.bundle from your 'plug-ins' directory.
1. Delete both Amsa directories from your 'plug-ins support/data' directory.
1. Delete and Amsa directories you find in your 'plug-ins support/cache' directory.
1. Extract the attached Amsa zip into your 'plug-ins' directory.
1. Start Plex

Lets see if that fixes it, if not then can you attach your logs for me.
[Amsa_Test.bundle_201703220045.zip](https://github.com/Dingmatt/AMSA/files/860054/Amsa_Test.bundle_201703220045.zip)

**Comment by begna112** [comment] 2017-03-22 23:46
I'm seeing a bunch of these, and similar :

`2017-03-22 18:42:49,483 (2b5a8fa44700) :  CRITICAL (storage:89) - Exception writing to /config/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.amsa_test/DataItems/Cache/AniDB\6970/6970.xml (most recent call last):
  File "/opt/plexmediaserver/Resources/Plug-ins-3b8374a5c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/storage.py", line 81, in save
    f = open(tempfile, mode)
IOError: [Errno 2] No such file or directory: '/config/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.amsa_test/DataItems/Cache/AniDB\\6970/._6970.xml'`

[com.plexapp.agents.amsa_test.log.zip](https://github.com/Dingmatt/AMSA/files/863223/com.plexapp.agents.amsa_test.log.zip)

I think the bundle is trying to make the directory, but it can't because it's using the Windows folder backslash instead of the Linux forward slash.

**Comment by begna112** [comment] 2017-03-22 23:48
In fact, when I do a directory list:

`root@Tower:/mnt/user/appdata/binhex-plexpass/Plex Media Server# ls -la
total 8
drwxrwxr-x 1 nobody users  330 Mar 22 18:37 ./
drwxrwxr-x 1 nobody users  106 Mar 12 21:17 ../
drwxrwxr-x 1 nobody users  270 Mar 22 18:37 Cache/
drwxrwxr-x 1 nobody users   84 Mar 21 18:16 Codecs/
drwxrwxr-x 1 nobody users   80 Mar 21 18:16 Crash\ Reports/
drwxrwxr-x 1 nobody users 2682 Mar 22 18:38 Logs/
drwxrwxr-x 1 nobody users   18 Mar 12 21:15 Media/
drwxr-xr-x 1 nobody users   16 Mar 12 21:30 Metadata/
drwxrwxr-x 1 nobody users  100 Mar 12 21:11 Plug-in\ Support/
drwxrwxrwx 1 nobody users   10 Mar 21 18:16 Plug-in\ Support\\Data\\com.plexapp.agents.amsa_test\\DataItems/
drwxrwxr-x 1 nobody users   62 Mar 22 18:37 Plug-ins/
-rw------- 1 nobody users  905 Mar 22 18:37 Preferences.xml
drwxrwxr-x 1 nobody users   12 Mar 12 21:17 Scanners/
-rw-r--r-- 1 nobody users    2 Mar 22 18:37 plexmediaserver.pid
`

It created that file there because it couldn't make the folder correctly.

**Comment by Dingmatt** [comment] 2017-03-22 23:50
@begna112 Ok now that makes sense, I didn't consider Linux when coding the static paths; I should be able to get a fix out for you pretty quickly.

**Comment by begna112** [comment] 2017-03-22 23:54
I do suggest looking at those logs, though. There are a few places where I see some double \\ and multiple locations failing because of the slashes. 

I'll test again once you've got the fix :)

**Comment by Dingmatt** [comment] 2017-03-23 03:02
Hi @begna112, can you try this version for me. Is should be OS agnostic as I've reworked and links / double slashes to work with the inbuilt python OS functions.

Many thanks,
 
[Amsa_Test.bundle_201703230233.zip](https://github.com/Dingmatt/AMSA/files/863508/Amsa_Test.bundle_201703230233.zip)

**Comment by begna112** [comment] 2017-03-23 03:08
This looks promising! http://i.imgur.com/gEaPahJ.jpg

**Comment by Dingmatt** [comment] 2017-03-23 12:29
@begna112 @sven-7 @namaless If everyone's now getting at least an initial set of metadata I'm going to close this, we can create additional tickets for separate issue moving forward.

**Comment by sven-7** [comment] 2017-03-23 12:43
Yes, on my last test I was. Will try the latest and open a ticket if anything pops up.

**Closed** 2017-03-23 12:45 UTC
