### ISSUE TITLE
AMSA Demo 6 Results

### ISSUE THREAD

**Issue by sven-7** [Dingmatt/AMSA#2] opened 2017-04-14 01:27 UTC
@Dingmatt  -- sorry for some delays.  Here are the results of a first test.

- No Posters for 91 Days.  Season description, but no episode descriptions.
- No Match:  The Disastrous Life of Saiki K, Garo - The Crimson Moon, Mobile Suit Gundam - The Origin
- TVDB4 (Ushio and Tora, Bungo Stray Dogs) -- no posters or episode metadata
- TVDB3 (Gintama) - No episode titles or descriptions (Other TVDB3 shows okay)

[com.plexapp.agents.amsa_test.log.zip](https://github.com/Dingmatt/AMSA/files/921221/com.plexapp.agents.amsa_test.log.zip)

**Comment by Dingmatt** [comment] 2017-04-14 11:10
@sven-7 Thanks for the feedback.
Its seems that the 91 Days  issue was caused by a bug in Python itself, I've included the documented work around so that should hopefully fix it. 

As for the matches, they seem to work on my system so I'm going to assume that it was a cascading issue caused by the first bug; can you update to the version attached and try again for me. 

[Amsa_Test.bundle_201704141202.zip](https://github.com/Dingmatt/AMSA/files/921959/Amsa_Test.bundle_201704141202.zip)

The issues with TVDB3/4 are to be expected as neither of those custom structures are supported yet (TVDB3 is partially supported but only due to luck atm), I'll be adding support before ending the demo's but I'm focusing on improving the agents efficiency first (as its core code). With this in mind could you send me over a zipped version of your AMSA bundles directory as it'll help me add in that support when I start working on it.

**Comment by sven-7** [comment] 2017-04-14 21:25
Bundles attached.

Re 91 Days - I wonder if I'm having that issue with HAMA as well.  I often run HAMA and no posters get pulled down on the first run.  After a refresh they do.  Is this the same?

RE TVDB3/4 - no worries, thanks for letting me know.

[Bundles.zip](https://github.com/Dingmatt/AMSA/files/922983/Bundles.zip)

**Comment by Dingmatt** [comment] 2017-04-14 21:27
@sven-7 I'll pass the info over to ZeroQI.

**Comment by sven-7** [comment] 2017-04-14 23:03
Awesome! Yes, if you could pass that I think both could benefit. 

I was careful not to add all shows at once to avoid the ban just in case, but it definitely worked smoothly and didn't ban me.

**Comment by Dingmatt** [comment] 2017-04-16 14:12
@sven-7 I'm going to close this as we can open issues for TvDB3/4 when I start coding there support.

**Closed by Dingmatt** 2017-04-16 14:12 UTC
